### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Code-Sploit** [Code-Sploit/Feint#1]
- [ ] Improve error handling
- [ ] Add loops
- [ ] Add arrays
- [x] Make a pre-run syntax checker
- [x] Improve documentation
- [ ] Improve compiler argument options
- [ ] Add input()
- [x] Make self-defined function callable
- [x] Add multiple function support
- [ ] **Make independent of NASM**
